version: "3.9"
services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:15.3.0
    user: root
    environment:
      POSTGRESQL_PASSWORD: "adminpwd"
      POSTGRESQL_DATABASE: "titans"
    volumes:
      - ./database:/bitnami/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d titans"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    user: root
    image: dpage/pgadmin4:7.1
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpwd"
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - 5050:5050
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - postgres



  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=gbtitan
      - RABBITMQ_DEFAULT_PASS=developer
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
    networks:
      - postgres

  nginx:
    image: nginx:1.23-bullseye-perl
    container_name: nginx
    ports:
      - 8082:80
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - postgres

# ldap:
#    image: itzg/apacheds
#    user: root
#    container_name: ldap
#    ports:
#      - 389:10389
#    volumes:
#      - ./ads:/ads
#    networks:
#      - postgres

  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=4 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.0.0.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ~/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - postgres


networks:
  postgres:
    driver: bridge
